
#spring
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mstar
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-while-idl: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev

logging:
  level:
    com.mlatin.spcc.service.impl: trace
    com.mlatin.spcc.controller: trace