server:
  port: 8080

spring:
  application:
    name: spcc
  profiles:
    active: local

mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体类扫描，多个的话用逗号或者分号隔开隔开
  type-aliases-package: com.mlatin.codegen.mapper
  # 枚举扫描类  # 支持统配符 * 或者 ; 分割
  type-enums-package:  com.mlatin.enums
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"未设置",2:"用户输入ID", 3:"分配ID (主键类型为number或string）";
      id-type: id_worker
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #逻辑删除字段  默认无，设置回自动扫描该字段
      #      logic-delete-field:
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql

      #刷新mapper 调试神器
      refresh-mapper: true

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

logging:
  config: classpath:logback-spring.xml

# 去除启动信息打印的 CONDITIONS EVALUATION REPORT
logging.level.org.springframework.boot.autoconfigure: ERROR
